---
- hosts: 127.0.0.1
  connection: local
  tasks:  
    - name: Create service
      nsxt_services:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "{{ item.display_name }}"
        nsservice_element: "{{ item.nsservice_element }}"
        state: "{{ item.state | default('present') }}"
      with_items:
        - "{{ nsxt_services }}"
    - name: Create a new IP Set
      nsxt_ip_sets:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "{{ item.display_name }}"
        ip_addresses: "{{ item.ip_addresses }}"
        state: "{{ item.state | default('present') }}"
      with_items:
        - "{{ nsxt_ip_sets }}"
    - name: Create a new NS Group
      nsxt_ns_groups:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "{{  item.display_name  }}"
        membership_criteria: "{{ item.membership_criteria | default([]) }}"
        members: "{{ item.members | default([]) }}"
        state: "{{ item.state | default('present') }}"
      with_items:
        - "{{ nsxt_ns_groups }}"
    - name: Create DFW Section with Rules
      nsxt_firewall_section_with_rules:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "{{ item.display_name }}"
        rules: "{{ item.rules | default([]) }}"
        state: "{{ item.state | default('present') }}"
        stateful: "{{ item.stateful | default(True) }}"
      with_items:
        - "{{ nsxt_firewall_section }}"